# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: CI/CD
on:
  push:
    branches: [ feat/*, feat/** ]
  pull_request:
    branches: [ feat/* ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: clean and build
      env:
        PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY  }}
        HOST_NAME: ${{ secrets.HOST_NAME  }}
        USER_NAME: ${{ secrets.USER_NAME  }}
      run: |
        ./gradlew clean build
        echo "$PRIVATE_KEY" > devOooops.pem
        cat devOooops.pem
        chmod 600 devOooops.pem
        scp -i devOooops.pem build/libs/dev-Oooops-api-*.war ${{secrets.USER_NAME}}@${{secrets.HOST_NAME}}:/opt/dev-oooops/
        pwd






